language: node_js
node_js:
  - node

before_deploy:
  - tsc
  - mkdir out
  - mv *css *.html lib/ out/
deploy:
  local-dir: out
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
